defaults: &defaults
  region:     'ap-northeast-1'
  endpoint:   'sqs.ap-southeast-1.amazonaws.com'
  queue_url:  'https://sqs.ap-northeast-1.amazonaws.com/xxxxxxxxxxxx'
  queue_name: 'test_queue'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
